### ISSUE TITLE
Preparing EuRoC for self-calibration

### ISSUE THREAD

**Issue by YasuThompson** [TRI-ML/vidar#12]
Hi. 
Thank you for preparing your great work. 

Where can I download EuRoC dataset in a form suitable for running the self-calibration code?
Or where can I find the split file for the dataset?

**Comment by KOuldamer** [comment]
Thank you very much,

Have you shared the code of Self-Calibration from Video partage ?

**Comment by VitorGuizilini-TRI** [comment]
You can use this config file to train on EUROC using UCM: 
https://github.com/TRI-ML/vidar/blob/a306e23cc47ae05a0c35b0bf8acf7112c87c049c/configs/papers/selfcalib/ucm_euroc.yaml

**Comment by KOuldamer** [comment]
Thank you

**Comment by yhabib29** [comment]
> You can use this config file to train on EUROC using UCM: https://github.com/TRI-ML/vidar/blob/a306e23cc47ae05a0c35b0bf8acf7112c87c049c/configs/papers/selfcalib/ucm_euroc.yaml

Can you give more details on the pre-process please ? What changed from the original dataset ?
