### ISSUE TITLE
Parallel Domain dataset 

### ISSUE THREAD

**Issue by hemangchawla** [TRI-ML/vidar#31]
Hello,

I am unable to download the ParallelDomain dataset from the provided link (https://paralleldomain.com/public-datasets)
I use:  `curl -s https://tri-ml-public.s3.amazonaws.com/github/vidar/datasets/PD_guda.tar | tar xv -C vidar/`

The link to the dataset appears to be broken/ incorrect. 

Could you please assist?

**Comment by VitorGuizilini-TRI** [comment]
Hi, we have a new datasets repository here: https://github.com/tri-ml/efm_datasets.  It will soon include direct links to our published datasets, including this one.
