### ISSUE TITLE
How to learn camera intrinsics for DepthFormer?

### ISSUE THREAD

**Issue by tommiekerssies** [TRI-ML/vidar#34]
I want to train on videos from different cameras (e.g. random YouTube videos). How do I get the camera intrinsics? The paper states they can be learned. Is there code to do this? Can I use the self-calibration code for that perhaps? Or will performance still be reasonable without learning the intrinsics?

**Comment by 1005452649** [comment]
hello,can I have a look at your code? @tommiekerssies

**Comment by tommiekerssies** [comment]
I don't have any code yet

**Comment by 1005452649** [comment]
How do I get the camera intrinsics? @VitorGuizilini-TRI @IgorVasiljevic-TRI

**Comment by VitorGuizilini-TRI** [comment]
For DepthFormer we do not learn camera intrinsics, so you need to provide those alongside the images. We have some other works that include camera self-calibration, you could perhaps run those first, get the predicted intrinsics, and feed them to DepthFormer. That would be an interesting thing to try!

**Comment by 1005452649** [comment]
Where is the code for camera self-calibration? @VitorGuizilini-TRI

**Comment by VitorGuizilini-TRI** [comment]
You can self-calibrate on KITTI using this script, let me know if it works out for you: https://github.com/TRI-ML/vidar/blob/main/configs/papers/selfcalib/ucm_kitti.yaml
