### ISSUE TITLE
How to perform camera self-calibration?

### ISSUE THREAD

**Issue by 1005452649** [TRI-ML/vidar#40]
@VitorGuizilini-TRI @IgorVasiljevic-TRI

**Comment by marcnunez** [comment]
up

**Comment by 1005452649** [comment]
hello,Will you help me with this problem? @VitorGuizilini-TRI @IgorVasiljevic-TRI

**Comment by VitorGuizilini-TRI** [comment]
There are some example scripts on `configs/papers/selfcalib`, I hope those help!

**Comment by MichaelWangGo** [comment]
> There are some example scripts on `configs/papers/selfcalib`, I hope those help!

Hi thank your for the excellent work! But how to train a .yaml file? I think there should be a train.py or something like that.
