### ISSUE TITLE
Inconsistency on PackNet and DepthFormer datasets and evaluation results

### ISSUE THREAD

**Issue by HoangChuongNguyen** [TRI-ML/vidar#42]
In the paper of PackNet, the reported Abs Rel is 0.162. In the GitHub repository for [PackNet](https://github.com/TRI-ML/packnet-sfm) (self-supervised), the Abs Rel is reported as 0.173, attributed to the updated DDAD dataset. This repository suggests other methods to compare with the new result, instead of the old one. However, the DepthFormer paper states a result of PackNet's Abs Rel as 0.162, which appears to be an old result.

I have few questions here: 
- Was DepthFormer trained on the old dataset (where PackNet's Abs Rel is 0.162), or was it trained on the new dataset (where PackNet's Abs Rel is 0.173)?
- If DepthFormer was trained on the old dataset, is the currently released [dataset](https://github.com/TRI-ML/DDAD) the new one or the old one?
- If the currently released dataset is the new one (where PackNet's Abs Rel is 0.173), could you also publish the old dataset, so that my model can be comparable to your model?

Thank you!

**Comment by VitorGuizilini-TRI** [comment]
Hi, we apologize for the confusion. The DepthFormer paper should have cited the updated DDAD numbers (with an Abs.Rel. of 0.173). We don't have the splits for the old dataset anymore, so all of our experiments are conducted with the new version (the one that is released). I hope this clarifies things!

**Comment by HoangChuongNguyen** [comment]
That clears things out. Thank you very much!
